{
	"FileBatchId": "0B9848C2-5DB5-43AE-B641-87272AF3ABDD",
	"PartnerId": "00000000-0000-0000-0000-000000000000",
	"PartnerName": "partner-test",
	"Files": [
		{
			"Id": "4ebd333a-dc20-432e-8888-bf6b94ba6d87",
			"Uri": "https://lasodevinsightsescrow.blob.core.windows.net/partner-test/SterlingNational_Laso_R_Demographic_11107019_11107019.csv",
			"ContentLength": 89885,
			"ETag": "0x8D7CB7471BA82AE",
			"DataCategory": "Demographic"
		}

	]

}