FROM databricksruntime/standard:latest

LABEL maintainer="LASO Data"

RUN mkdir -p /app


# Copy the requirements.txt first, for separate dependency resolving and downloading
COPY requirements.txt /app/

# copy the main entrypoint files for each app
COPY __dbs-main__.py /app/

RUN cd /app \
  && /databricks/conda/bin/pip install -r requirements.txt

# Copy the source code
#ONBUILD COPY . /app


# docker build --rm -t dataservices/data-quality . 
# docker run -it  --rm dataservices/data-quality bash 