{
	"CorrelationId": "0B9848C2-5DB5-43AE-B641-87272AF3ABDD",
	"PartnerId": "00000000-0000-0000-0000-000000000000",
	"PartnerName": "Demo Partner",
	"Files": [
		{
			"Id": "4Row_Boundary_2FailCreditScore.",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_4Row_Boundary_2FailCreditScore.csv",
			"Policy": "None",
			"DataCategory": "Demographic",
			"ETag": "0x8D7C9F4176A77B4"
		}
	],
	"Files_NOT_IN_USE": [
		{
			"Id": "10rows_1pass.",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/AccountTransaction_10rows_REDACTED_1pass.csv",
			"Policy": "None",
			"DataCategory": "AccountTransaction",
			"ETag": "0x8D7C9F4176A77B4"
		},
		{
			"Id": "TwoRow_Header_CorrectOrder.",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_TwoRow_Header_CorrectOrder.csv,",
			"Policy": "None",
			"DataCategory": "Demographic",
			"ETag": "0x8D7C9F4176A77B4"
		},
		{
			"Id": "full_as_it_is.",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_FULL.csv,",
			"Policy": "None",
			"DataCategory": "Demographic",
			"ETag": "0x8D7C9F4176A77B4"
		},
		{
			"Id": "4Row_Boundary_2FailCreditScore.",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_4Row_Boundary_2FailCreditScore.csv",
			"Policy": "None",
			"DataCategory": "Demographic",
			"ETag": "0x8D7C9F4176A77B4"
		}
	],
	"ProductId": "0B9848C2-5DB5-43AE-B641-87272AF3ABDD"
}




