{
	"PartnerId": "00000000-0000-0000-0000-000000000000",
	"Files": [
		{
			"Id": "TwoRow_Header_CorrectOrder",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/validcsv/Demographic_TwoRow_Header_CorrectOrder.csv",
			"DataCategory": "Demographic"
		},
		{
			"Id": "TwoRow_Header_CorrectOrder_LOWER",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/validcsv/Demographic_TwoRow_Header_CorrectOrder_LOWER.csv",
			"DataCategory": "Demographic"
		},
		{
			"Id": "TwoRow_Header_CorrectOrder_UPPER",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/validcsv/Demographic_TwoRow_Header_CorrectOrder_UPPER.csv",
			"DataCategory": "Demographic"
		},


		{
			"Id": "Laso",
			"Uri": "https://lasodevinsights.blob.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/validcsv/ValidCsvMatch_Laso_D_Demographic.csv",
			"DataCategory": "Demographic"
		},
		{
			"Id": "AllLower",
			"Uri": "https://lasodevinsights.blob.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/validcsv/ValidCsv_AllLower_D_Demographic.csv",
			"DataCategory": "Demographic"
		},
		{
			"Id": "AllUpper",
			"Uri": "https://lasodevinsights.blob.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/validcsv/ValidCsv_AllUpper_D_Demographic.csv",
			"DataCategory": "Demographic"
		},
		{
			"Id": "CamelCase",
			"Uri": "https://lasodevinsights.blob.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/validcsv/ValidCsv_CamelCase_D_Demographic.csv",
			"DataCategory": "Demographic"
		},

		{
			"Id": "SENTINEL",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/invalidcsv/Demographic_TwoRow_NoHeader.csv",
			"DataCategory": "Demographic"
		}
	]

}




