{
	"CorrelationId": "0B9848C2-5DB5-43AE-B641-87272AF3ABDD",
	"OrchestrationId": "0B9848C2-5DB5-43AE-B641-87272AF3ABDD",
	"PartnerId": "00000000-0000-0000-0000-000000000000",
	"PartnerName": "Demo Partner",
	"Files": [
		{
			"Id": "TwoRow_Header_CorrectOrder",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_TwoRow_Header_CorrectOrder.csv",
			"DataCategory": "Demographic"
		},
		{
			"Id": "TwoRow_Header_CorrectOrder_LOWER",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_TwoRow_Header_CorrectOrder_LOWER.csv",
			"DataCategory": "Demographic"
		},
		{
			"Id": "TwoRow_Header_CorrectOrder_UPPER",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_TwoRow_Header_CorrectOrder_UPPER.csv",
			"DataCategory": "Demographic"
		},		
		{
			"Id": "TwoRow_Header_IncorrectOrder",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_TwoRow_Header_IncorrectOrder.csv",
			"DataCategory": "Demographic"
		},
		{
			"Id": "TwoRow_NoHeader",
			"Uri": "https://lasodevinsights.dfs.core.windows.net/raw/00000000-0000-0000-0000-000000000000/test-data/Demographic_TwoRow_NoHeader.csv",
			"DataCategory": "Demographic"
		}
	]

}




