version: 1
disable_existing_loggers: True
formatters: 
    standard: 
        format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    extended:
        format: '%(asctime)s %(name)s %(levelname)s: %(message)s'  

handlers: 
    console:
        level: DEBUG
        formatter: standard
        class: logging.StreamHandler
        stream: 'ext://sys.stdout'  # Default is stderr
    file_handler:
        class: logging.FileHandler
        level: INFO
        filename: test.log
        formatter: extended

loggers: 
    __main__':  # if __name__ == '__main__'
        handlers: [console]
        level: DEBUG
        propagate: False
root:   # root logger
    handlers: [console]
    level: DEBUG
    propagate: False    
