hostingContext:
  appName: myapplication
  logLevel: WARN
vaults:
  insights:
    tenantId: "000000-0000-0000-0000-00000000"
    url: "https://kv-laso-dev-insights.vault.azure.net"
    clientId: "111111-1111-1111-1111-11111111"
    clientSecret: "{env:APPDATA}"
storage:
  accounts:
    escrow:
      accessType: "ConnectionString"
      connectionString: "long connection string"
    insights:            
      accessType: "ConnectionString"
      connectionString: "secret:insights:storage-insights-connectionstring"
  filesystems:
    escrow:
      account: escrow
      type: https
    raw:
      account: insights
      type: https
    rejected:
      account: insights
      type: https
