hostingContext:
  appName: myapplication
  logLevel: WARN
vaults:
  insights:
    authType: "ClientSecret"
    tenantId: "3ed490ae-eaf5-4f04-9c86-448277f5286e"
    url: "https://kv-laso-dev-insights.vault.azure.net"
    clientId: "e903b90d-9dbb-4c45-9259-02408c1c1800"
    clientSecret: "{env:Insights_KV_Secret}"
storage:
  accounts:
    escrow:
      accessType: "ConnectionString"
      connectionString: "long connection string"
    insights:            
      accessType: "ConnectionString"
      connectionString: "secret:insights:Connectionstrings-Storage-Insights"
  filesystems:
    escrow:
      account: escrow
      type: https
    raw:
      account: insights
      type: https
    rejected:
      account: insights
      type: https
