{
	"CorrelationId": "0B9848C2-5DB5-43AE-B641-87272AF3ABDD",
	"PartnerId": "93383d2d-07fd-488f-938b-f9ce1960fee3",
	"PartnerName": "Demo Partner",
	"Files": [
		{
			"Id": "4ebd333a-dc20-432e-8888-bf6b94ba6000",
			"Uri": "https://lasodevinsightsescrow.blob.core.windows.net/93383d2d-07fd-488f-938b-f9ce1960fee3/SterlingNational_Laso_R_AccountTransaction_11107019_11107019095900.csv",
			"ContentLength": 89885,
			"ETag": "0x8D7CB7471BA8000",
			"DataCategory": "AccountTransaction"
		}

	]

}