hostingContext:
  appName: myapplication
  logLevel: WARN
vaults:
  insights:
    credentialType: "ClientSecret"
    tenantId: "3ed490ae-eaf5-4f04-9c86-448277f5286e"
    url: "https://kv-laso-dev-insights.vault.azure.net"
    clientId: "e903b90d-9dbb-4c45-9259-02408c1c1800"
    clientSecret: "{env:LASO_INSIGHTS_DATAMANAGEMENT_SECRET}"
storage:
  accounts:
    escrow:
      credentialType: ConnectionString
      connectionString: "secret:insights:Connectionstrings-Storage-Escrow"
    insights:            
      credentialType: ConnectionString
      connectionString: "secret:insights:Connectionstrings-Storage-Insights"
  filesystems:
    escrow:
      account: escrow
      type: https
    raw:
      account: insights
      type: https
    rejected:
      account: insights
      type: https
servicebus:
  namespaces:
    insights:
      credentialType: ConnectionString
      connectionString: "secret:insights:Connectionstrings-ServiceBus-Insights"
  topics:
    router-trigger:
       topic: partnerfilesreceivedevent
       subscription: AllEvents

