#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

function log() {
    echo "[$0] $*" >&2
}

# execute all blobfuse mount scripts
if [ -d /etc/fuse.d ]; then
    for f in /etc/fuse.d/*; do
        if [ -x "$f" ]; then
            log "Running $f ..."
            $f
        else
            log "Could not run $f, because it's missing execute permission (+x)."
        fi
    done
    unset f
fi