FROM ubuntu:18.04

# fix locales
RUN apt-get update \
    && apt-get install -y --no-install-recommends locales \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV LANG en_US.utf8

# install python
RUN apt-get update && apt-get install -y python python-dev python3.7 python3.7-dev python-pip virtualenv libssl-dev libpq-dev git build-essential libfontconfig1 libfontconfig1-dev
RUN pip install setuptools pip --upgrade --force-reinstall

# update systemwide python link
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2 \
 && update-alternatives --install /usr/bin/python python /usr/bin/python3 1
 
# update Python environment variables
ENV PYTHONHASHSEED 0
ENV PYTHONIOENCODING UTF-8
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
 
# install java
RUN apt install openjdk-8-jre-headless -y
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

# install wget
RUN apt-get update -y \
 && apt-get install -y wget
 
RUN wget -O /usr/local/bin/goofys https://github.com/kahing/goofys/releases/latest/download/goofys \
 && chmod +x /usr/local/bin/goofys

# ==========END OF PREREQUISITES=================

# =================FUSE==========================
# install blobfuse
RUN apt-get update \
    && apt-get install -y wget apt-utils \
    && wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get remove -y wget \
    && apt-get update \
    && apt-get install -y --no-install-recommends fuse blobfuse libcurl3-gnutls libgnutls30 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /mnt/blobfusetmp && chmod 0777 /mnt/blobfusetmp

RUN mkdir /etc/blobcfg
COPY escrow-configuration.cfg /etc/blobcfg
RUN chmod 600 /etc/blobcfg/escrow-configuration.cfg

# ---------- RAW ------------
RUN mkdir /mnt/blobfusetmp/raw \
 && mkdir /mnt/raw && chmod 0777 /mnt/raw
COPY raw-configuration.cfg /etc/blobcfg
RUN chmod 600 /etc/blobcfg/raw-configuration.cfg

RUN mkdir /etc/blobcfg/insights
COPY insights-config.txt /etc/blobcfg/insights/config

# ---------- REJECTED ------------
RUN mkdir /mnt/blobfusetmp/rejected \
 && mkdir /mnt/rejected && chmod 0777 /mnt/rejected
COPY rejected-configuration.cfg /etc/blobcfg
RUN chmod 600 /etc/blobcfg/rejected-configuration.cfg

# ---------- CURATED ------------
RUN mkdir /mnt/blobfusetmp/curated \
 && mkdir /mnt/curated && chmod 0777 /mnt/curated
COPY curated-configuration.cfg /etc/blobcfg
RUN chmod 600 /etc/blobcfg/curated-configuration.cfg

# =================END FUSE==========================

# =================ENTRY==========================

COPY mount-blobfuse.sh /
RUN chmod 755 /mount-blobfuse.sh

ENTRYPOINT ["/mount-blobfuse.sh"]
# =================END ENTRY==========================
