FROM ubuntu:18.04

# fix locales
RUN apt-get update \
    && apt-get install -y --no-install-recommends locales \
    && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV LANG en_US.utf8

# install system utilities
RUN apt-get update -y \
 && apt-get install curl -y \
 && apt-get install wget -y \
 && apt-get install kmod -y

 RUN apt-get update -y \
 && apt-get install rsyslog -y

# install python
RUN apt-get update && apt-get install -y python python-dev python3.7 python3.7-dev python-pip virtualenv libssl-dev libpq-dev git build-essential libfontconfig1 libfontconfig1-dev
RUN pip install setuptools pip --upgrade --force-reinstall

# update systemwide python link
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2 \
 && update-alternatives --install /usr/bin/python python /usr/bin/python3 1
 
# update Python environment variables
# http://blog.stuart.axelbrooke.com/python-3-on-spark-return-of-the-pythonhashseed
ENV PYTHONHASHSEED 0
ENV PYTHONIOENCODING UTF-8
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
 
# install java
RUN apt install openjdk-8-jre-headless -y
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64


 
# ==========END OF PREREQUISITES=================

# ============= GOOFYS ==========================
# RUN wget -nv -O /usr/local/bin/goofys https://github.com/kahing/goofys/releases/latest/download/goofys \
#  && chmod +x /usr/local/bin/goofys


#RUN mkdir -p /etc/blobcfg
#COPY escrow-configuration.cfg /etc/blobcfg
#RUN chmod 600 /etc/blobcfg/escrow-configuration.cfg


# ENV AZURE_CONFIG_DIR /etc/blobcfg/insights 
# ===============================================


# ============= Azure CLI ==========================
RUN apt-get update \
 && apt-get install -y ca-certificates curl apt-transport-https lsb lsb-release gnupg

RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | \
    tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
    
# ENV AZ_REPO $(lsb_release -cs)
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main" | \
     tee /etc/apt/sources.list.d/azure-cli.list   

RUN apt-get update \
 && apt-get install azure-cli
# ===============================================

# ==========APPLICATION PREREQUISITES============
# PYTHON LIBRARIES
# RUN apt-get update -y \
#  && pip install cerberus pandas pyspark jsons \
#  && apt-get clean 

# ==========END OF APPLICATION PREREQUISITES=====

# HADOOP
ENV HADOOP_VERSION 3.2.1
ENV HADOOP_HOME /usr/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
ENV HADOOP_OPTIONAL_TOOLS hadoop-azure
ENV PATH $PATH:$HADOOP_HOME/bin
RUN curl -sL --retry 3 \
  "https://lasodevstorage.file.core.windows.net/install/Applications/Server/Apache/hadoop-3.2.1.tar.gz?st=2020-03-23T17%3A00%3A00Z&se=2025-03-23T05%3A00%3A00Z&sp=rl&sv=2018-03-28&sr=f&sig=OvHJ5OxGJmKgZ%2FMgJ7laawGzGiP8g178gl7xFDtWMAg%3D" \
  | gunzip \
  | tar -x -C /usr/ \
 && rm -rf $HADOOP_HOME/share/doc \
 && chown -R root:root $HADOOP_HOME

# http://www.gtlib.gatech.edu/pub/apache/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-without-hadoop.tgz
# https://www.apache.org/dyn/closer.lua/spark/spark-2.4.5/spark-2.4.5-bin-without-hadoop.tgz
# https://www.apache.org/dyn/closer.lua/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-without-hadoop.tgz
# https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/${SPARK_PACKAGE}.tgz
# SPARK
ENV SPARK_VERSION 2.4.5
ENV SPARK_PACKAGE spark-${SPARK_VERSION}-bin-without-hadoop
ENV SPARK_HOME /usr/spark-${SPARK_VERSION}
ENV PYSPARK_PYTHON /usr/bin/python
ENV PYSPARK_DRIVER_PYTHON /usr/bin/python
ENV SPARK_DIST_CLASSPATH="$HADOOP_HOME/etc/hadoop/*:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/hdfs/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/yarn/lib/*:$HADOOP_HOME/share/hadoop/yarn/*:$HADOOP_HOME/share/hadoop/mapreduce/lib/*:$HADOOP_HOME/share/hadoop/mapreduce/*:$HADOOP_HOME/share/hadoop/tools/lib/*"
ENV PATH $PATH:${SPARK_HOME}/bin
RUN curl -sL --retry 3 \
  "https://lasodevstorage.file.core.windows.net/install/Applications/Server/Apache/spark-2.4.5-bin-without-hadoop.tgz?st=2020-03-23T05%3A00%3A00Z&se=2025-03-23T05%3A00%3A00Z&sp=rl&sv=2018-03-28&sr=f&sig=lRi%2BDmTeVKi9gU5JUggrbMwWLUS8khqhQU3oRopqcz0%3D" \
  | gunzip \
  | tar x -C /usr/ \
 && mv /usr/$SPARK_PACKAGE $SPARK_HOME \
 && chown -R root:root $SPARK_HOME
ENV ENABLE_INIT_DAEMON true
ENV INIT_DAEMON_BASE_URI http://identifier/init-daemon
ENV INIT_DAEMON_STEP spark_master_init

# setup HDFS filesystem for insights
COPY core-site.xml /usr/hadoop-$HADOOP_VERSION/etc/hadoop

# ==============END OF HADOOP/SPARK======================

# =================FUSE==========================
# install blobfuse
RUN apt-get update \
    && apt-get install -y wget apt-utils \
    && wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get remove -y wget \
    && apt-get update \
    && apt-get install -y --no-install-recommends fuse blobfuse libcurl3-gnutls libgnutls30 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /mnt/blobfusetmp && chmod 0777 /mnt/blobfusetmp
RUN mkdir -p /etc/blobfuse.conf.d \
 && chmod 600 /etc/blobfuse.conf.d

# ---------- ESCROW ------------
RUN mkdir -p /mnt/blobfusetmp/escrow \
 && mkdir -p /dbfs/mnt/escrow \
 && chmod 0777 /dbfs/mnt/escrow
COPY escrow-configuration.cfg /etc/blobfuse.conf.d
RUN chmod 600 /etc/blobfuse.conf.d/escrow-configuration.cfg

# ---------- RAW ------------
RUN mkdir -p /mnt/blobfusetmp/raw \
 && mkdir -p /dbfs/mnt/raw \
 && chmod 0777 /dbfs/mnt/raw
COPY raw-configuration.cfg /etc/blobfuse.conf.d
RUN chmod 600 /etc/blobfuse.conf.d/raw-configuration.cfg

# ---------- REJECTED ------------
RUN mkdir -p /mnt/blobfusetmp/rejected \
 && mkdir -p /dbfs/mnt/rejected \
 && chmod 0777 /dbfs/mnt/rejected
COPY rejected-configuration.cfg /etc/blobfuse.conf.d
RUN chmod 600 /etc/blobfuse.conf.d/rejected-configuration.cfg

# ---------- CURATED ------------
RUN mkdir -p /mnt/blobfusetmp/curated \
 && mkdir -p /dbfs/mnt/curated \
 && chmod 0777 /dbfs/mnt/curated
COPY curated-configuration.cfg /etc/blobfuse.conf.d
RUN chmod 600 /etc/blobfuse.conf.d/curated-configuration.cfg

# =================END FUSE==========================

# =================ENTRY==========================

COPY mount-blobfuse.sh /
RUN chmod 755 /mount-blobfuse.sh

ENTRYPOINT ["/mount-blobfuse.sh"]
# =================END ENTRY==========================
