hostingContext:
  appName: "Data Quality"
  logLevel: DEBUG
vaults:
  insights:
    credentialType: "ClientSecret"
    tenantId: "3ed490ae-eaf5-4f04-9c86-448277f5286e"
    url: "https://kv-laso-dev-insights.vault.azure.net"
    clientId: "e903b90d-9dbb-4c45-9259-02408c1c1800"
    clientSecret: "{env:LASO_INSIGHTS_DATAMANAGEMENT_SECRET}"

runtime:
    encryptOutput: true
    internalFilesystemType: dbfs

storage:
  encryptionPolicies:
    laso:
      encryptionRequired: True
      cipher: AES_CBC_256
      vault: insights
      keyId: "Encryption-BlobAes256Key"

  accounts:
    insights:            
      storageAccount: lasodevinsights
      dnsname: lasodevinsights.dfs.core.windows.net
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-Storage-Insights}"
  filesystems:
    raw:
      account: insights
      type: abfss
      retentionPolicy: default
      encryptionPolicy: laso
    rejected:
      account: insights
      type: abfss
      retentionPolicy: default
      encryptionPolicy: laso
    curated:
      account: insights
      type: abfss
      retentionPolicy: default
      encryptionPolicy: laso

servicebus:
  namespaces:
    insights:
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-ServiceBus-Insights}"
  topics:
    runtime-trigger:
       topic: dataqualitycommand
       subscription: AllEvents
    runtime-status:
       namespace: insights
       topic: datapipelinestatus

quality:
    csv:
        strict: False
        min_data_rows: 0
        header_check_row_count: 10
