hostingContext:
  appName: "Data Router"
  logLevel: DEBUG

vaults:
  insights:
    credentialType: "ClientSecret"
    tenantId: "3ed490ae-eaf5-4f04-9c86-448277f5286e"
    url: "https://kv-laso-dev-insights.vault.azure.net"
    clientId: "e903b90d-9dbb-4c45-9259-02408c1c1800"
    clientSecret: "{env:LASO_INSIGHTS_DATAMANAGEMENT_SECRET}"

runtime:
    encryptOutput: true
    internalFilesystemType: https
    delete: True

storage:
  encryptionPolicies:
    laso:
      encryptionRequired: True
      cipher: AES_CBC_256
      vault: insights
      keyId: "Encryption-BlobAes256Key"

  accounts:
    escrow:
      storageAccount: lasodevinsightsescrow
      dnsname: lasodevinsightsescrow.blob.core.windows.net
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-Storage-Escrow}"
    archive:
      storageAccount: lasodevinsightscold
      dnsname: lasodevinsightscold.blob.core.windows.net
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-Storage-Archive}"
    insights:            
      storageAccount: lasodevinsights
      dnsname: lasodevinsights.dfs.core.windows.net
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-Storage-Insights}"

  filesystems:
    escrow:
      account: escrow
      type: https
      retentionPolicy: default
    archive:
      account: archive
      type: https
      retentionPolicy: default-archive
    raw:
      account: insights
      type: abfss
      retentionPolicy: default
      encryptionPolicy: laso

servicebus:
  namespaces:
    insights:
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-ServiceBus-Insights}"
  topics:
    runtime-trigger:
       topic: partnerfilesreceivedevent
       subscription: AllEvents
    runtime-status:
       namespace: insights
       topic: datapipelinestatus
