hostingContext:
  appName: "Data Router"
  logLevel: DEBUG

vaults:
  insights:
    credentialType: "ClientSecret"
    url: "{dbrsecret:application:key_vault_url}"
    # App Registration with access to the key vault, i.e. laso-???-insights-datamanagement:
    tenantId: "{dbrsecret:application:azure_identity_tenant_id}"    
    clientId: "{dbrsecret:application:azure_identity_client_id}"
    clientSecret: "{dbrsecret:application:azure_identity_client_secret}"

runtime:
    encryptOutput: true
    internalFilesystemType: https
    delete: False

storage:
  encryptionPolicies:
    laso:
      encryptionRequired: True
      cipher: AES_CBC_256
      vault: insights
      keyId: "Encryption-BlobAes256Key"

  accounts:
    escrow:
      storageAccount: "{dbrsecret:application:escrow_storage_account}" 
      dnsname: "{dbrsecret:application:escrow_storage_account_dnsname}"
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-Storage-Escrow}"
    archive:
      storageAccount: "{dbrsecret:application:cold_storage_account}" 
      dnsname: "{dbrsecret:application:cold_storage_account_dnsname}"
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-Storage-Archive}"
    insights:            
      storageAccount: "{dbrsecret:application:insights_storage_account}" 
      dnsname: "{dbrsecret:application:insights_storage_account_dnsname}"
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-Storage-Insights}"

  filesystems:
    escrow:
      account: escrow
      type: https
      retentionPolicy: default
    archive:
      account: archive
      type: https
      retentionPolicy: default-archive
    raw:
      account: insights
      type: abfss
      retentionPolicy: default
      encryptionPolicy: laso

servicebus:
  namespaces:
    insights:
      credentialType: ConnectionString
      connectionString: "{secret:insights:Connectionstrings-ServiceBus-Insights}"
  topics:
    runtime-trigger:
       topic: partnerfilesreceivedevent
       subscription: AllEvents
    runtime-status:
       namespace: insights
       topic: datapipelinestatus
